### ISSUE TITLE
Click on the Hidden button does not work

### ISSUE THREAD

**Issue by Christiangnuxyz** [elramidreju/Playnite-DuplicateFinder#1] opened 2024-10-24 15:37 UTC
Hi 
the click on the Hidden button does not work on Playnite version 10.34 on Windows 11 23H2
https://github.com/user-attachments/assets/1f6e8804-2046-4044-94cb-1018f1c7e817

**Comment by elramidreju** [comment] 2024-10-27 22:44
Hi! Thank you for opening this issue!

This is not really a bug. That checkbox in your video is just how the 'Hidden' value is displayed in the results list, but it is not interactable. 

For now, the expected usage was to find duplicates using Duplicate Finder, and then using the main library view to hide or remove those games.

I admit this is not great UX so, while I am closing this issue as it is not a bug, I have opened #2 and #3 to outline how this process can be improved. I will be taking on those as soon as I find time, but you (or anyone eventually reading) are more than welcome to give them a try if you want.

Sorry for the inconvenience, and thank you again for writing!

**Closed as completed by elramidreju** 2024-10-27 22:44 UTC
